# Generated by Django 4.2.1 on 2023-09-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='path',
            field=models.CharField(default='', max_length=500),
        ),
    ]
