# Generated by Django 4.2.1 on 2023-10-31 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_news_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
